py_binary(
    name = "tryWebserver",
    srcs = ["tryWebserver.py"],
    main = "tryWebserver.py",
    visibility = ["//visibility:public"],
    deps = [
         "//utils/src/python:py_utils",
         "//fetch_teams/bottle:bottle",
    ],
    data = [
    ]
)
