py_library(
    name="lib",
    visibility = ["//visibility:public"],
    srcs = glob(["*.py"]),
    deps = [
        "//dap_api/src/python:dap_api",
        "//api/src/proto:py_api_pb",
        "//fetch_teams/oef_core_protocol:py_oef_protocol",
    ],
    data = [
    ],
)
