py_library(
    name = "async_socket",
    srcs = glob(["*.py"]),
    visibility = ["//visibility:public"],
    srcs_version = "PY3",
    deps = [
        "//network/src/proto:py_network_pb",
        "//api/src/python:interfaces"
    ]
)