py_binary(
    name = "foo",
    srcs = ["main.py"],
    main = "main.py",
    visibility = ["//visibility:public"],
    deps = [
         "//bazel_play/src/python/lib:lib",
         "//utils/src/python:py_utils",
    ],
    data = [
    ]
)
