py_binary(
    name = "app",
    srcs = ["main.py"],
    main = "main.py",
    visibility = ["//visibility:public"],
    deps = [
         "//optimframe/src/python/openpopgrid:openpopgrid",
    ],
    data = [
    ]
)

