py_binary(
    name = "main",
    srcs = ["main.py"],
    main = "main.py",
    visibility = ["//visibility:public"],
    deps = [
         "//optimframe/src/python/openpopgrid:openpopgrid",
         "//optimframe/src/python/node:self_org_node",
         "//optimframe/src/python/lib:lib",
    ]
)
