py_binary(
    name = "one",
    srcs = ["one.py"],
    main = "one.py",
    visibility = ["//visibility:public"],
    deps = [
         "//optimframe/src/python/openpopgrid:openpopgrid",
         "//optimframe/src/python/lib:lib",
    ],
)
