py_library(
    name = "search_engine",
    srcs = ["SearchEngine.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//fetch_teams/oef_core_protocol:py_oef_protocol",
        "//utils/src/python:py_utils",
        "//dap_api/src/python:dap_api",
        "//dap_api/src/python/network:dap_network"
    ]
)
