py_library(
    name = "app",
    srcs = glob(["*.py"]),
    visibility = ["//visibility:public"],
    deps = [
        "//dap_api/src/python:dap_api",
        "//dap_api/experimental/python:experimental_lib",
        "//dap_api/src/protos:py_dap_api_pb",
    ],
)
