py_binary(
        name="agentbehaviour",
        visibility = ["//visibility:public"],
        deps=[
             "//behaviour_tree/src/python/lib:lib",
             "//crawler_demo/src/python/lib:lib",
        ],
        srcs=["agentbehaviour.py"],
        main="agentbehaviour.py",
)
