py_binary(
    name = "node_test",
    srcs = ["NodeTest.py"],
    main = "NodeTest.py",
    visibility = ["//visibility:public"],
    deps = [
         "//optimframe/src/python/openpopgrid:openpopgrid",
         "//optimframe/src/python/node:self_org_node"
    ],
)
