py_library(
        name="dap_api",
        visibility = ["//visibility:public"],
        srcs = glob(["*.py"]),
        deps=[
                "@com_google_protobuf//:protobuf_python",
                "//dap_api/src/protos:py_dap_api_pb",
        ],
)
