py_binary(
    name = "foo",
    srcs = ["main.py"],
    main = "main.py",
    visibility = ["//visibility:public"],
    deps = [
         "//england_grid/src/python/lib:lib",
    ],
    data = [
         "//england_grid/resources/images:pop-images",
    ]
)
