py_library(
    name = "sync_socket",
    srcs = glob(["*.py"]),
    visibility = ["//visibility:public"],
    srcs_version = "PY3",
    deps = [
        "//network/src/proto:py_network_pb",
        "//network/src/python/async_socket:async_socket",
        "//api/src/python:interfaces",
        "//utils/src/python:py_utils"
    ]
)