cc_library(
    name = "cpp_dap_utils",
    visibility = [
        "//visibility:public",
    ],
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    deps = [
         "//cpp-sdk/src/cpp:lib",
         "//cpp-sdk/experimental/protos:cc_dap_config_pb"
    ],
)
