py_binary(
        name="testapp",
        visibility = ["//visibility:public"],
        deps=[
                "//src/python/testapp/mainfuncs:mainfuncs",
                "//src/protos/testapp:py_testapp_pb",
        ],
        srcs=["testapp.py"],
)
